# Generated by Django 5.2
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="Skill", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(max_length=120, unique=True)), ("category", models.CharField(max_length=80)),
            ("description", models.TextField(blank=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="JobRole", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("title", models.CharField(max_length=160, unique=True)), ("slug", models.SlugField(max_length=180, unique=True)),
            ("description", models.TextField())], options={"ordering": ["title"]}),
        migrations.CreateModel(name="JobSkillRequirement", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("required_level", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ("importance", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ("job_role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_requirements", to="core.jobrole")),
            ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="job_requirements", to="core.skill"))],
            options={"ordering": ["job_role", "-importance", "skill"], "unique_together": {("job_role", "skill")}}),
        migrations.CreateModel(name="UserSkill", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("level", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ("session_key", models.CharField(blank=True, max_length=128)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_skills", to="core.skill")),
            ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="skill_records", to="auth.user"))],
            options={"ordering": ["-created_at", "skill"]}),
        migrations.CreateModel(name="LearningResource", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("title", models.CharField(max_length=200)), ("url", models.URLField()),
            ("resource_type", models.CharField(choices=[("course", "Course"), ("documentation", "Documentation"), ("project", "Project"), ("book", "Book"), ("video", "Video")], max_length=20)),
            ("level", models.CharField(choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")], max_length=20)),
            ("is_free", models.BooleanField(default=False)), ("notes", models.TextField(blank=True)),
            ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="learning_resources", to="core.skill"))],
            options={"ordering": ["skill", "level", "title"]}),
        migrations.AddField(model_name="jobrole", name="skills", field=models.ManyToManyField(related_name="job_roles", through="core.JobSkillRequirement", to="core.skill")),
    ]
